### ISSUE TITLE
[BUG] Bad roll distribution

### ISSUE THREAD

**Issue by Monadic-Cat** [spenserblack/one-d-six-rs#8]
`(r % max) + 1` is used in in all the roll methods, where `r` is a randomly generated
integer of the type in use. This is incorrect wherever the integer type maximum is not evenly divisible by `max`.

This can be corrected by using the `Rng::gen_range(lower_inclusive, upper_exclusive)` function from the `rand` crate.

**Comment by spenserblack** [comment]
Thanks for the report!
I've set the milestone for this issue to be v1.0.0, but this will most likely get rolled into a 0.2.2 or 0.3.0 release.
